image: gitlab/dind

services:
  - docker:dind

stages:
  - deploy
  
deploy-heroku:
  stage: deploy
  script: docker login --username=_ --password=1502b53d-72ed-4218-941d-d95595a12c24 registry.heroku.com && docker build -t registry.heroku.com/fierce-temple-56849/web . && docker push registry.heroku.com/fierce-temple-56849/web
  tags:
    - docker


    
 


 
