image: gitlab/dind

services:
  - docker:dind

stages:
  - build
  - test
  - container
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install --prefix ./NodeDevOps/
  artifacts:
    paths:
      - node_modules/
  tags:
    - build

testing_testing:
  stage: test
  script: npm test --prefix ./NodeDevOps/
  tags:
    - test

build-container:
  stage: container
  script: docker build -t registry.gitlab.com/juanrodriguezarc/nodedevops . && docker push registry.gitlab.com/juanrodriguezarc/nodedevops
  tags:
    - docker

deploy-heroku:
  stage: deploy
  script: docker login --username=_ --password=1502b53d-72ed-4218-941d-d95595a12c24 registry.heroku.com && docker build -t registry.heroku.com/fierce-temple-56849/web . && docker push registry.heroku.com/fierce-temple-56849/web
  tags:
    - docker


    
 


 
