image: node:latest

stages:
  - build
  - test
  - container

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install --prefix ./NodeDevOps/
  artifacts:
    paths:
      - node_modules/
  tags:
    - build

testing_testing:
  stage: test
  script: npm test --prefix ./NodeDevOps/
  tags:
    - test

build-container:
  stage: container
  script: docker build -t registry.gitlab.com/juanrodriguezarc/nodedevops . && docker push registry.gitlab.com/juanrodriguezarc/nodedevops
  tags:
    - docker